apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-mongodb-app
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-mongodb-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ITG-jnadlaon/s2i-sample.git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:18-ubi8
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: s2i-mongodb-app:latest      
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2i-mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s2i-mongodb-app
  template:
    metadata:
      labels:
        app: s2i-mongodb-app
    spec:
      containers:
      - name: s2i-mongodb-app
        image: s2i-mongodb-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://appuser:secretpass123@mongodb:27017/myapp"
        - name: MONGODB_DATABASE
          value: "myapp"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: s2i-mongodb-app
spec:
  selector:
    app: s2i-mongodb-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: s2i-mongodb-app
spec:
  to:
    kind: Service
    name: s2i-mongodb-app
