apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.redhat.io/rhscl/mongodb-36-rhel7:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_USER
          value: "appuser"
        - name: MONGODB_PASSWORD
          value: "secretpass123"
        - name: MONGODB_DATABASE
          value: "myapp"
        - name: MONGODB_ADMIN_PASSWORD
          value: "adminpass123"
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
